apiVersion: v1
kind: Service
metadata:
  name: activity-service
  namespace: default 
  labels:
    app: activity-service
spec:
  ports:
  - port: 8080
  selector:
    app: activity-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
  namespace: default 
  labels:
    app: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
      - name: activity-service
        image: docker.io/jumkid/activity-service:0.9.0
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: MYSQL_DATABASE_CONNECTION 
          value: jdbc:mysql://mysql:3306
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
