apiVersion: v1
kind: Service
metadata:
  name: content-vault
  namespace: default 
  labels:
    app: content-vault
spec:
  ports:
  - port: 8080
  selector:
    app: content-vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-vault
  namespace: default 
  labels:
    app: content-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-vault
  template:
    metadata:
      labels:
        app: content-vault
    spec:
      containers:
      - name: content-vault
        image: docker.io/jumkid/content-vault:1.0.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        env:
        - name: ELASTICSEARCH_HOSTS 
          value: http://elasticsearch:9200
        ports:
        - containerPort: 8080
        imagePullPolicy: Always 
        volumeMounts:
        - name: content-vault-persistent-storage
          mountPath: "/opt/content-vault/data"
      volumes:
      - name: content-vault-persistent-storage
        persistentVolumeClaim:
          claimName: content-vault-pv-claim  
