apiVersion: v1
kind: Service
metadata:
  name: integration-hub
  namespace: default 
  labels:
    app: integration-hub
spec:
  ports:
  - port: 8080
  selector:
    app: integration-hub
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-hub
  namespace: default 
  labels:
    app: integration-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-hub
  template:
    metadata:
      labels:
        app: integration-hub
    spec:
      containers:
      - name: integration-hub
        image: docker.io/jumkid/integration-hub:0.0.1
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
