apiVersion: v1
kind: Service
metadata:
  name: kafka-cluster
  labels:
    app: kafka-broker
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-broker
    id: "0"
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
        app: kafka
        id: "0"
  template:
    metadata:
      labels:
        app: kafka
        id: "0"
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        resources:
          limits:
            memory: 512Mi
            cpu: 0.5
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "30718"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.1.240
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs  
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1