apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
spec:
  ports:
  - port: 9092
    name: kf-port
    protocol: TCP
  selector:
    app: kf-broker
    id: "0"
  type: LoadBalancer
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kf-broker
spec:
  replicas: 1
  selector:
    app: kf-broker
  template:
    metadata:
      labels:
        app: kf-broker
        id: "0"
    spec:
      containers:
      - name: kf-broker
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        resources:
          limits:
            memory: 1Gi
            cpu: 0.5
        env:
        - name: KAFKA_LOG_DIRS
          value: /kafka/kafka-logs  
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper-cluster:2181
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INSIDE://:9092,OUTSIDE://kf-cluster:30322"
        - name: KAFKA_LISTENERS
          value: "INSIDE://:9092,OUTSIDE://:30322"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"   