apiVersion: v1
kind: Service
metadata:
  name: zookeeper-cluster
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: kf-zookeeper
status:
  loadBalancer: {}
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kf-zookeeper
spec:
  replicas: 1
  selector:
    app: kf-zookeeper      
  template:
    metadata:
      labels:
        app: kf-zookeeper
    spec:
      containers:
      - name: kf-zookeeper
        image: zookeeper:3.4.13
        ports:
        - containerPort: 2181
        - containerPort: 2888
        - containerPort: 3888
        resources:
          limits:
            memory: 256Mi
            cpu: 0.1
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zoo1
        - name: ZOOKEEPER_SERVER_2
          value: zoo2  