apiVersion: v1
kind: Service
metadata:
  name: content-vault
  namespace: default 
  labels:
    app: content-vault
spec:
  http:
      service:
        spec:
          type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: content-vault
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-vault
  namespace: default 
  labels:
    app: content-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-vault
  template:
    metadata:
      labels:
        app: content-vault
    spec:
      containers:
      - name: content-vault
        image: docker.io/jumkid/content-vault:1.0.1
        env:
        - name: ELASTICSEARCH_HOST
          value: content-vault-es-http
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: ELASTICSEARCH_USERNAME
          value: elastic
        - name: ELASTICSEARCH_PASSWORD
          value: nUpcl46dWf6895qf8xaP00j7
        - name: ELASTICSEARCH_KEYSTORE_PATH
          value: keystore/truststore.p12
        - name: ELASTICSEARCH_KEYSTORE_PASSWORD
          value: bigdata
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        volumeMounts:
        - name: content-vault-persistent-storage
          mountPath: "/opt/content-vault/data"
      volumes:
      - name: content-vault-persistent-storage
        persistentVolumeClaim:
          claimName: content-vault-pv-claim
